[package]
name = "ultra_queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
serde = { version = "1.0.158", features = ["derive"] }
sha2 = "0.10.6"
tokio = { version = "1.26.0", features = ["full"] }
